#pragma once

#define ENABLE_SERIAL (1)  // Must be LOGICAL OR of all of below.

#define DEBUG_PRINT_INITIALIZATION (1)
#define DEBUG_PRINT_TEENSYID (1)
#define DEBUG_PRINT_XBEE_TIMING (0)
#define DEBUG_PRINT_XBEE_RECEIVE (0)
#define DEBUG_PRINT_XBEE_SEND (0)
#define DEBUG_PRINT_NEOKEYCR (0)
