#pragma once

#define I_WANT_DEBUG (0)
#define DEBUG_PRINT_INITIALIZATION (1)
#define DEBUG_PRINT_XBEE_TIMING (0)
#define DEBUG_PRINT_XBEE_RECEIVE (0)
#define DEBUG_PRINT_XBEE_SEND (0)
#define DEBUG_PRINT_TEENSY_ID (0)
#define DEBUG_PRINT_NEOKEYCR (1)
