#pragma once

#include "bounce_walk.h"
#include "free.h"
#include "idle.h"
#include "piv_spin.h"
#include "pivot.h"
#include "pivseq.h"
#include "random_mags.h"
#include "set_mags.h"
#include "set_phis.h"
#include "wait.h"
#include "walk.h"
#include "walk_to_dir.h"

// #include "diamond.h"
// #include "do_preset.h"
// #include "orbit.h"
// #include "shear.h"
// #include "sufi.h"
// #include "walk_to_pos.h"
// #include "walk_to_pos_in_field.h"
